build:
 <% if (build.githubRepository.getPullRequest(DOTCI_PULL_REQUEST.toInteger()).listFiles().collect { it.filename }.contains(".ci.yml")) { %>
 run:  echo  meow
 <%} else {%>
 run:  echo <%= build.githubRepository.getPullRequest(DOTCI_PULL_REQUEST.toInteger()).listFiles().collect { it.filename } %>
 <%}%>

environment: 
  language: java

