build:
 <% if (build.githubRepository.getPullRequest(1).listFiles().asList().contains(".ci.yml")) { %>
 run:  echo <%= build.githubRepository.getPullRequest(1).listFiles().asList() %>
 <%} else {%>
 run: echo meow
 <%}%>

environment: 
  language: java

