<% changed_files = build.githubRepository.getPullRequest(DOTCI_PULL_REQUEST.toInteger()).listFiles().collect { it.filename } %>
build:
 <% if (DOTCI_PULL_REQUEST && changed_files.contains(".ci.yml")) { %>
 run:  echo <% changed_files %> 
 <%} else {%>
 run:  echo purr 
 <%}%>

environment: 
  language: java

