BuildTags:
   shouldBuildTags: true
JobUi:
   newUi: false
RebuildSettings:
   autoRebuild: true
   rebuildDisabled: false
BuildTimeoutWrapper: 
    strategy: 
       $class: hudson.plugins.build_timeout.impl.AbsoluteTimeOutStrategy
       timeoutMinutes: 10
   
