build:
 <% if (DOTCI_PULL_REQUEST && build.githubRepository.getPullRequest(DOTCI_PULL_REQUEST.toInteger()).listFiles().collect { it.filename }.contains(".ci.yml")) { %>
 run:  echo  meow
 <%} else {%>
 run:  echo purr 
 <%}%>

environment: 
  language: java

