mongo:
  image: mongo:3

mavendata:
  image: ubuntu:14.04
  volumes:
    - ~/.m2:/root/.m2
    - ~/.ivy2:/root/.ivy2

plugin:
  build: .
  volumes_from:
    - mavendata
  volumes:
    - .:/code
  links:
    - mongo
  working_dir: /code
  ports:
    - "8080:8080"
  environment:
    BOWER_ALLOW_ROOT: 'True'
    MAVEN_OPTS: "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=n"
  command: mvn hpi:run
 
ci:
  image: maven:3
  volumes_from:
    - mavendata
  volumes:
    - .:/code
  working_dir: /code
  command: mvn test
