#
#The MIT License (MIT)
#
#Copyright (c) 2014, Groupon, Inc.
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in
#all copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#THE SOFTWARE.
#
parent_template: install_packages
environment:
  language: ruby
  language_versions: 1.9.3_p392

  vars:
    RACK_ENV: test
    RAILS_ENV: test
    BUNDLE_PATH: /tmp/bundle_cache/`echo $WORKSPACE | awk -F "/" '{print \$5"/"\$6}'`/`jruby -v 2>&1 | awk '{print \$1"-"\$2}' | grep jruby || ruby -v | awk '{print \$1"-"\$2}'`/bundle_cache
    BUNDLE_FROZEN: true
    BUNDLE_WITHOUT: production:development
    BUNDLER_VERSION: 1.9.9
    GEM_HOME: /tmp
    PATH: $GEM_HOME/bin:$PATH

build:
  info:
    - gem env
  before:
    - 'test -f Gemfile && [[ "`gem env gempath`" =~ jruby ]] && export RUN_AS_JRUBY="jruby -S"'
    - test -f Gemfile && $RUN_AS_JRUBY gem install bundler -v $BUNDLER_VERSION
    - test -f Gemfile && $RUN_AS_JRUBY bundle install --no-deployment -j 10

  run:
    - test -f Gemfile && $RUN_AS_JRUBY bundle exec rake
